# 00 Artificial Neural Network

In [11]:
import numpy as np

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [12]:
x = np.array([1, 0.5])
x.shape

(2,)

In [13]:
w1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
w1.shape

(2, 3)

In [14]:
np.dot(x, w1).shape

(3,)

In [15]:
b1 = np.array([0.1, 0.2, 0.3])
b1.shape

(3,)

In [16]:
a1 = np.dot(x, w1)+b1

In [17]:
a1

array([0.3, 0.7, 1.1])

In [52]:
z1 = sigmoid(a1)

In [53]:
z1

array([0.57444252, 0.66818777, 0.75026011])

In [55]:
z1.shape

(3,)

# second layer

In [56]:
w2 = np.array([[0.8, 0.32, 0.2, 0.5], [0.6, 0.5, 0.75, 0.95], [0.3, 0.1, 0.35, 0.25]])  
b2 = np.array([1.0, 0.8, 0.95, 0.87]) 


In [57]:
b2.shape

(4,)

In [58]:
a2 = np.dot(z1, w2) + b2  # linear combination
z2 = sigmoid(a2)  # apply the sigmoid activation function

a2

In [59]:
a2

array([2.08554471, 1.3929415 , 1.82862037, 1.97956467])

In [60]:
z2

array([0.88949024, 0.80106142, 0.86159729, 0.87863475])

In [116]:
w3 = np.array([[0.1],[0.2],[0.3], [0.4]])
b3 = np.array([0.14091 ])

In [117]:
w3.shape

(4, 1)

In [118]:
w3

array([[0.1],
       [0.2],
       [0.3],
       [0.4]])

In [119]:
b3

array([0.14091])

In [120]:
a3 = np.dot(z2, w3) + b3

In [121]:
print(a3)

[1.0000044]
